### ISSUE TITLE
Ambiguous parentheses

### ISSUE THREAD

**Issue by cscherrer** [hakaru-dev/hakaru#107]
Simplify [`naive_bayes.hk`](https://github.com/hakaru-dev/tcp/blob/master/src/NaiveBayes/naive_bayes.hk) yields code that includes this expression:
```
(product i from 0 to size(topic_prior):
  product iB from 0 to size(word_prior):
  product j
  from 0
  to summate iF from 0 to size(w):
     if docUpdate == doc[iF]: if i == zNewf && iB == w[iF]: 1 else: 0
     else: 0:
  nat2prob
    (summate iF from 0 to size(w):
     if doc[iF] == docUpdate: 0
     else: if i == z[doc[iF]] && iB == w[iF]: 1 else: 0)
  + nat2prob(j)
  + word_prior[iB])
```

Since the `product`s are not in parentheses, it's not clear where their scope ends. `nat2prob(j)` contains `j`, so it must belong to the innermost product. But what about `word_prior[iB]`? The scoping is not clear, and affects the resulting value.

**Request:**
This should be easy to fix. When the code is pretty-printed, could `product`s be enclosed with parentheses, like this:
```
(product i from lo to hi:
  f(i)
)
```

Thank you

**Comment by ccshan** [comment]
Does it help to declare that `product` and `summate` and `fn` bind as far to the right as possible?

**Comment by cscherrer** [comment]
Yes, that helps. So for example,
```
product i from 0 to 10:
i
+
product j from 0 to 10:
j
```

means (counterintuitively, to me at least)

```
product i from 0 to 10:
  (i + product j from 0 to 10: j)
```

Is that right?

**Comment by ccshan** [comment]
Yes.
