### ISSUE TITLE
How to simplify away trivial (branches of) partitions?

### ISSUE THREAD

**Issue by ccshan** [hakaru-dev/hakaru#108]
As noted in discussion at https://github.com/hakaru-dev/hakaru/commit/e65bda5c895ebe19f9a79f045e8e5fbf2cbd2b3d , we want to simplify partitions with branches whose conditions contain `true` or `false`. The analogous simplification for `piecewise` is performed by `eval`. How do we do this for `Partition`?

**Comment by yuriy0** [comment]
I believe the correct thing to do is to perform the desired simplification in `eval/PARTITION`. That is done [here](4ece4589e7fb7368410796ba14afd56a2b950a43). With this change and reverting e65bda5, gmm_gibbs simplify to the same program.

Can this branch be merged into master, or are there other issues standing in the way?

**Comment by JacquesCarette** [comment]
Do all the rest of the tests continue to pass/fail as before?

**Comment by yuriy0** [comment]
They do indeed; both Maple tests and Haskell tests (except for the newly added gmm_gibbs on the Haskell side, whose output is changed by this branch).

**Comment by JacquesCarette** [comment]
Then I am definitely all for integrating this.

**Comment by ccshan** [comment]
Yes, this change should be merged into `master`, whether along with the rest of `kronecker_in_simplify` (soon?) or now.
