### ISSUE TITLE
v0.5 release

### ISSUE THREAD

**Issue by zaxtax** [hakaru-dev/hakaru#111]
Can I make a 0.5 release? It looks like transforms have been merged in. What are we waiting on?

**Comment by ccshan** [comment]
If I recall correctly, we agreed that a v0.5 release can be made as soon as the thermometer, gmm, and naive_bayes workflows are tested and working.

**Comment by zaxtax** [comment]
Ah ok. I had thought there was something else in addition to those things.

**Comment by JacquesCarette** [comment]
And, AFAIK, Geneva is waiting on you guys to comment on her work (possibly answer some questions) to finish parts of that.

**Comment by yuriy0** [comment]
> as soon as the thermometer, gmm, and naive_bayes workflows are tested and working

As of 7be783df01f87ff9551dd102936674ed240aa7d4, the test suite contains these, and they pass.

**Comment by GenevaS** [comment]
Documentation to-dos are in #92

**Comment by JacquesCarette** [comment]
It seems like 0.5 was released. So should this be closed? Looks like to docs are still not quite done, but they have their own issue.
