### ISSUE TITLE
Hanging when feeding a measure to a distribution

### ISSUE THREAD

**Issue by maymoo99** [hakaru-dev/hakaru#113]
The following program hangs after generating a (seemingly) random number of values:
```
def gammaPoisson(shape prob, scale prob) measure(nat):
	mu <~ gamma(shape, scale)
	X <~ poisson(mu)
	return X

gammaPoisson(1.0,1.0)
```
I suspect it has to do with the fact that we are feeding a measure from one distribution into the parameter of another distribution.

**Comment by zaxtax** [comment]
That shouldn't be a problem. I mean Hakaru was meant to do stuff like that :)

The issue seems to be that this program is making the poisson random number generator go into an infinite loop. But I have definitely replicated this bug!

**Comment by zaxtax** [comment]
I just pushed a change. Can you confirm if the program works now?

**Comment by maymoo99** [comment]
Yep! After pulling the changes and reinstalling hakaru (i.e. running `stack install`) the program is working as expected. Thank you!
