### ISSUE TITLE
Expect doesn't go under case

### ISSUE THREAD

**Issue by wrengr** [hakaru-dev/hakaru#16]
When we try to compute the expectation of a case-expression where the scrutinee cannot be evaluated far enough to match some branch (e.g., because the scrutinee is a neutral term), right now we will residualize the call to expect around the whole case expression. What we would much rather do is to push the transformation down into all the branches.

**Comment by wrengr** [comment]
@zaxtax is there a specific commit that closes this? Or any comment about things that do/don't work? Tests that check for regressions?

**Comment by zaxtax** [comment]
I would claim 9dad92ca969c30b793d85e862d441d21ea3c9801 fixed it.
