### ISSUE TITLE
improve Sing :: Symbol -> *

### ISSUE THREAD

**Issue by wrengr** [hakaru-dev/hakaru#19]
The singletons package has an implementation of `Sing :: Symbol -> *` which avoids the need for storying a `Proxy` [(cf)](http://hackage.haskell.org/package/singletons-2.1/docs/Data-Promotion-Prelude.html#t:Symbol). We'd like to do that too.

The main sticking point is that the `JmEq1` instance currently uses `TL.sameSymbol` which hard-codes needing a `Proxy` rather than being polymorphic over any type constructor (à la `TL.symbolVal`). `TL.sameSymbol` is implemented via `TL.symbolVal` and `unsafeCoerce`, so we can simply inline the definition if we don't mind maintaining the use of `unsafeCoerce` against future changes. The alternative is to send a patch upstream for liberalizing the type of `TL.sameSymbol`, and then waiting for new releases of GHC.

Thoughts?

**Comment by zaxtax** [comment]
I think we can both inline our improved definition, and should send a patch upstream.
