### ISSUE TITLE
Telling Maple size :: Array -> Nat.

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#20]
Somehow we need to add this information to our knowledge base, and make use of it in deductions.

**Comment by ccshan** [comment]
@zaxtax Would you please give a more concrete example (like an input to simplification) why we want to tell Maple size returns non-negative?

**Comment by zaxtax** [comment]
Sure suppose you have the following program

```
[zv@t420 hakaru (master)]% cat hello.hk                                                                                                                                                                                                   
fn x array(real):
 θ <~ normal(0,1)
 _ <~ plate i of size(x):
        observe normal(θ, 1) x[i]
 return θ
```

When we normalize and simplify it we get the following

```
[zv@t420 hakaru (master)]% simplify hello.hk | normalize | simplify -                                                                                                                                                                     
fn x array(real): 
 weight((match (signum(prob2real(((nat2prob(size(x)) * 1/2) + 1/2)))
                 == 
                1): 
          true: 1
          false: 0 * 
         ((nat2prob(size(x)) + 1) ** (1/2)) * 
         (recip(nat2prob((size(x) + 1))) ** (1/2))),
        normal(prob2real((recip(nat2prob((size(x) + 1))) * 
                          summate i from 0 to (nat2real(size(x)) + -1): 
                           real2prob(x[int2nat(i)]))),
               (recip(nat2prob((size(x) + 1))) ** (1/2))))
```

I believe this could simplify better if simplify knew that size(x) will never be negative.

**Comment by JacquesCarette** [comment]
Great example.

There are two different pieces of information we want in the above:
1. i is in bounds (so it can be used to index into x)
2. size(n) >= 0.

Information about (1) is used in very different ways than (2).  For (2) we could just as easily gensym a new name and make it known that it is non-negative.  That is probably the easiest solution.  We just need to a) keep track of that equality, likely in KB, and b) un-substitute on our way out.

I will readily grant that this is a bit of a hack.  I have been thinking about how to teach maple about the 'size' function, which would be a much more satisfying way of doing it.  But I don't quite know how to do that reliably yet, so the hack might be a reasonable intermediate measure.  [pun intended?]

**Comment by ccshan** [comment]
My commit 006bbc354e893bf364c07094f6e4cc6815bab359 achieves Jacques's (2).

```
$ .cabal/bin/simplify hello.hk | .cabal/bin/normalize | .cabal/bin/simplify -
fn x array(real): 
 normal(prob2real((recip(nat2prob((size(x) + 1))) * 
                   summate i from 0 to (nat2real(size(x)) + -1): 
                    real2prob(x[int2nat(i)]))),
        (recip(nat2prob((size(x) + 1))) ** (1/2)))
```
