### ISSUE TITLE
Parser problem

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#26]
fn k nat:
      x <~ plate _ of k:
        return 1
      return size(x)

gives
simplify: getTermSing: the impossible happened

which I'm guessing is a parser bug?

Something gets sent to Maple.  And it comes back.  There is a problem with this "measure", but that should not trigger an 'impossible happened' ?

**Comment by JacquesCarette** [comment]
fn k nat:
      x <~ plate i of k:
        uniform(0,1)
      return size(x)

which is less bogus, gives the same error.

**Comment by zaxtax** [comment]
Both work fine for me. Are you sure you have the latest version built?

**Comment by JacquesCarette** [comment]
I did not.  That error is gone now.

I don't really want to close this bug (yet) though.  I would rather wait until there's an automated test in our test suite that test these examples.  But I guess we don't have any such test suite yet!  Might be as good a time as any to start one?  [Not sure which testing framework to use; Haskell's isn't great, so some other one might be better.]

**Comment by zaxtax** [comment]
I think we can add these programs to Roundtrip. It's not a parser issue,
they parsed just fine. It was getTermSing not having a case.

**Comment by JacquesCarette** [comment]
You are mis-understanding me.

The 'bug' I reported is long fixed, I agree.  However, we should still take this bug report and make it into a regression test, before we mark it closed.  It's an old habit of mine: no bug ever gets marked closed until an explicit regression test is built and integrated into the test suite.  Even bug reports that are not-bugs, just to record that someone cared that input X worked properly, so that it doesn't stop working in the future.

**Comment by zaxtax** [comment]
Oh I don't think I came across clearly. I totally agree we should have a
regression test for this problem. I was remarking that the existing
infrastructure for
writing tests for Hakaru is good enough to add that test.

**Comment by JacquesCarette** [comment]
Cool.  I'd like to see how - I don't how I'd write "external syntax" tests (yet).

**Comment by zaxtax** [comment]
We have a function testWithConcrete which takes concrete syntax as input
let's you assert something about it.

https://github.com/hakaru-dev/hakaru/blob/master/haskell/Tests/TestTools.hs

If there is any interest I can make something that consumes concrete Hakaru
files instead.

**Comment by JacquesCarette** [comment]
I was definitely hoping for the latter.  Something that allows us to test all the external commands (like simplify, normalize, etc).

**Comment by zaxtax** [comment]
I don't know what you mean by test the external commands. The commands are just the functions plus parsing, typechecking, pretty printing. Wouldn't it be better to split those out into things that test each of those parts?

**Comment by JacquesCarette** [comment]
I mean scripts or something like that.  There are unit tests (testing each piece on its own), which should be done in Haskell tests.  Then there are 'system' tests, which should be done completely externally to the system, and test that all the pieces work together to give the expected answer.

**Comment by zaxtax** [comment]
I think the testConcreteFiles function added with cce1e66 should address this issue.
