### ISSUE TITLE
Improve pretty printing (Concrete.hs)

### ISSUE THREAD

**Issue by wrengr** [hakaru-dev/hakaru#27]
The following things should be done to help improve legibility of pretty printing to the concrete syntax:

- [x] When encountering `RealPow e (-1/n)` replace with `Recip (NatRoot e n)`. N.B., this is the negative case which isn't currently handled.
- [x] Since `NatRoot e 2` is so common, pretty print as `sqrt e` instead. N.B., make sure that `sqrt` is defined for symbol resolution too.
- [x] When encountering `e1 + -e2` pretty print as `e1 - e2` instead. N.B., should handle both the case where `e2` is `negate e3` as well as the case where `e2` is a negative literal.
- [x] When encountering `e1 * 1/e2` pretty print as `e1 / e2`; again both for `recip e3` and for literal `1/v3`.

**Comment by JacquesCarette** [comment]
Agreed.  I would have done this as 6 separate issues, so that they can be dealt with (and closed) independently.

**Comment by wrengr** [comment]
yeah, I talked with @zaxtax and asked if he had a preference, and he preferred them all as one ticket. ::shrug::

**Comment by zaxtax** [comment]
Yes! They all seem short and related.

Thanks for this list!

**Comment by zaxtax** [comment]
Actually @wrengr the last two bullet points look trickier, may I move them into their own issue?

**Comment by wrengr** [comment]
@zaxtax sure, go for it
