### ISSUE TITLE
bern -> categorical

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#29]
Translate primBern (in Haskell) to Categorical rather than Superpose.  

Rationale:  The invariants for Categorical are easier to establish than MSum.  Basically because Categorical involves a data-flow piecewise while MSum involves a control-flow piecewise.  So NewSLO will do much more simplifcation on the latter.

**Comment by zaxtax** [comment]
Just to be clear `bern` is a distribution over Bools, while `categorical` is a distribution over Nats. Are we proposing to change `bern` to be overs Nats as well?

**Comment by JacquesCarette** [comment]
Good point.  @ccshan what do you think?

I keep forgetting that bern is on Bool and Categorical is on Nat.  To me, bern should be any 2-element set, and Categorical on any (ordered!) n-element set.  That set should be specified as part of the distribution.  As wikipedia says "A categorical distribution is a discrete probability distribution whose sample space is the set of k individually identified items."  That that set is isomorphic to 1..k or 0..k-1 is not a good enough reason to make it so by fiat.

Of course, in the eventual "inner core" code that gets manipulate by Maple, this identification should have happened, and be invisible.  What we need, I think, is a translation layer, like the one currently in place for lambdas.

In the meantime, we still have a problem: right now, bern is translated using a control piecewise, while it would benefit a lot from using a dataflow piecewise.  What's the best way to achieve that?

**Comment by ccshan** [comment]
I agree that the most pressing issue is to switch bern from a control piecewise to a data piecewise. The first thing I would try, but not while driving, is to use categorical to express bern, and as Rob says, to switch bern over to nat.

**Comment by ccshan** [comment]
(And if it turns out that we need `bern` to range over `bool`, or more generaly if we need anything isomorphic to `categorical` to range over anything other than `nat`, then try to express it as follows: `Bind(Categorical([p,1-p]), i, Ret(idx([true,false],i)))`

**Comment by JacquesCarette** [comment]
On 2016-07-18T14:22:10-0400, Jacques Carette wrote:
> If I've got things right, I believe that defining Bern as
> Bern := proc(p) Bind(Counting(0,1), i, Weight(idx([p,1-p],i) * Ret(i))) end;
> would lead to the most simplifications.
>
> If we want true/false, then I believe that
> Bern := proc(p) Bind(Counting(0,1), i, Weight(idx([p,1-p],i) *
> Ret(idx([false, true],i)))) end;
> would be the way to go.
>
> Note that this generalizes very easily to categorical.

Indeed, the following two definitions already cause NewSLO:-toLO today
to produce the same patently linear expression:

    Bern := proc(p) Bind(Counting(0,1), i, Weight(idx([p,1-p],i), Ret(i))) end;

    Bern := proc(p) Categorical([p,1-p]) end;

**Comment by ccshan** [comment]
My current conclusion as to how to express bern in terms of categorical is at https://list.indiana.edu/sympa/arc/ppaml-l/2016-07/msg00089.html

**Comment by JacquesCarette** [comment]
So, modulo the translation to internal Haskell syntax, that's what should be implemented?  If I try to do it, how will I know that I have not broken anything -- i.e. what's the current way to run the Haskell-side test?  And will running that also run the .hk files?

**Comment by zaxtax** [comment]
There is Haskell syntax for literal arrays, but it is currently a macro.

The two main things which need to happen on the Haskell side is that we
need to update the AST with something for literal arrays, and Parser/Maple
needs to recognize these literals. Both of those are very doable, though I
don't know whether I'm putting literal Arrays with the Literals or ArrayOps.

**Comment by JacquesCarette** [comment]
So you're saying I should not implement Ken's literal-array-free suggestion and wait for literal arrays to land in Hakaru?

**Comment by zaxtax** [comment]
If you want something that works today I would suggest implementing Ken's
suggestion. We can change it when I merge in literal arrays.

**Comment by JacquesCarette** [comment]
@ccshan now or later on this?

**Comment by ccshan** [comment]
@zaxtax @JacquesCarette Who wants anything related to bern now?

Correct me if I'm wrong, but it seems implementing literal-array syntax is more important than implementing anything related to bern. First, the Maple side can already generate literal arrays (e.g., recognizing categorical) even if the Haskell side does not send any literal arrays to the Maple side. Second, bern can be a user-defined function like dirichlet is in some of the `examples`.

**Comment by pravnar** [comment]
The commits 0e5056cad91a8f8bc97bfe57d60e95990ba201bf and 8d9711f390d6273a4718ea4c9390c746d1721662 introduce literal arrays.

The commit 75dde2d12e98e8b01fe41a06353afde5996d76a0 redefines bern in terms of categorical.
