### ISSUE TITLE
avoid calling buggy `convert/piecewise`

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#31]
Ken says:

>   I'm thinking we'd keep the call in KB:-assert_deny and remove the call in Loop:-intssums.

I assigned it to 3 people, whoever gets to it first should close this issue.

**Comment by ccshan** [comment]
By the way, here's a less severe problem I just hit in `convert/piecewise` as called in `KB:-assert_deny`:

```
> try convert(piecewise(i<=size[idx[a,i]]-2,true,false),piecewise,i); catch: print(caught); end try
Error, (in unknown) too many levels of recursion
```

**Comment by JacquesCarette** [comment]
Why do you say 'less severe'?  For one thing, the try/catch *didn't*, so this bug can't be worked around!

You are using convert/piecewise as a proxy for normalizing (simplifying, whatever you want to call it) boolean expressions, right?  Yes, it does seem to work that way, sometimes, in more powerful ways than other routines.  But maybe we should be more precise about the questions we ask.

Anyways, you should probably file an SCR about this bug.
