### ISSUE TITLE
Scoping issue in the generated C code

### ISSUE THREAD

**Issue by sabauma** [hakaru-dev/hakaru#41]
The generated C code produces references to variables not declared in the current scope for the naive bayes example after ANF conversion. I am reasonably certain this is not due to a bug in the ANF pass.

The offending code can be seen at the bottom of this report. Note that the variable `_fo` is used outside its declared scope. My suspicion is that this is caused by the variable mapping in the `CodeGenMonad` being stored in a `State` monad. For the Hakaru AST, where identifiers are not globally unique, the proper definition of `CodeGenMonad` would thread the variable mapping through as a `Reader` monad. This prevents shadowing of variable definitions while sequentially traversing the AST.

Here is some sample code which illustrates the issue. Since ANF introduces many `let`-bindings, this problem is much more likely to occur (or may have to do with how the ANF pass generates new variables).

```Haskell
let x = 10
in (let x = 5 in x) + x -- This x points to ---+ in the variable mapping during code generation
        ^                                      |
        |                                      |
        +--------------------------------------+
```

I think there are two possible fixes:

1. Rework the `CodeGenMonad` to include a `Reader` layer in the stack and manage the variable mapping through said layer.
2. Have the C backend require globally unique `varID`s. There is a [pass](https://github.com/sabauma/hakaru/blob/optimizations/haskell/Language/Hakaru/Syntax/Uniquify.hs) in the `optimizations` branch which does this already, though it is not currently used. Running this pass before code generation fixes this problem.

```C
   for (i18_eu = _es; i18_eu < _et; i18_eu++)
   {
      double _ew;
      unsigned int _ex;
      struct arrayNat arr_ey;
      double _ez;
      unsigned int _f0;
      unsigned int _f1;
      unsigned int _f2;
      unsigned int i13_f3;
      unsigned int acc_f4;
      double p_fy;
      double _fz;
      unsigned int _g0;
      double p_g1;
      double _g2;
      unsigned int _g3;
      unsigned int _g4;
      unsigned int i13_g5;
      double acc_g6;
      double _ga;
      double _gb;
      double _gc;
      arr_ey = w_d;
      _ex = arr_ey.size;
      _f1 = 0;
      _f2 = _ex;
      acc_f4 = 0;
      /* ------------- Summate ------------- */
      for (i13_f3 = _f1; i13_f3 < _f2; i13_f3++)
      {
        unsigned int _f5;
        unsigned int _f6;
        struct arrayNat arr_f7;
        unsigned int _f8;
        struct SUSUV _f9;
        unsigned int _fa;
        unsigned int _fb;
        struct SUSUV _fc;
        unsigned int _fd;
        struct arrayNat arr_fe;
        unsigned int _ff;
        struct SUSUV _fg;
        unsigned int _fh;
        unsigned int _fi;
        struct SUSUV _fj;
        struct SUSUV not_fk;
        unsigned int _fl;
        struct arrayNat arr_fm;
        unsigned int _fn;
        unsigned int _fo;
        struct arrayNat arr_fp;
        unsigned int _fq;
        struct SUSUV _fr;
        unsigned int _fs;
        unsigned int _ft;
        struct SUSUV _fu;
        struct SUSUV _fv;
        struct SUSUV _fw;
        struct SUSUV _fx;
        arr_f7 = doc_e;
        _f8 = i13_f3;
        _f6 = (*(arr_f7.data + _f8));
        _fa = _f6;
        _fb = docUpdate_f;
        _f9.index = (_fa == _fb) ? 0 : 1;
        _fc = _f9;
        if ((_fc.index == 0))
        {
          _f5 = 0;
        }
        if ((_fc.index == 1))
        {
          arr_fe = w_d;
          _ff = i13_f3;
          _fd = (*(arr_fe.data + _ff));
          _fh = _fd;
          _fi = 0;
          _fg.index = (_fh < _fi) ? 0 : 1;
          not_fk = _fg;
          not_fk.index = (not_fk.index == 1) ? 0 : 1;
          arr_fm = doc_e;
          _fn = i13_f3;
          _fl = (*(arr_fm.data + _fn));
          arr_fp = z_c;
          _fq = _fl;
          _fo = (*(arr_fp.data + _fq));
          _fs = i_dv;
          _ft = _fo;
          _fr.index = (_fs == _ft) ? 0 : 1;
          _fv = _fj;
          _fw = _fr;
          _fu.index = (!(_fw.index == _fv.index));
          _fx = _fu;
          if ((_fx.index == 0))
          {
            _f5 = 1;
          }
          if ((_fx.index == 1))
          {
            _f5 = 0;
          }
        }
        acc_f4 += _f5;
      }
      _f0 = acc_f4;
      p_fy = log1p((_f0 - 1));
      _ez = p_fy;
      _g0 = i18_eu;
      p_g1 = log1p((_g0 - 1));
      _fz = p_g1;
      _g3 = 0;
      _g4 = word_prior_size_j;
      acc_g6 = log(0);
      /* ------------- Summate ------------- */
      for (i13_g5 = _g3; i13_g5 < _g4; i13_g5++)
      {
        double _g7;
        struct arrayProb arr_g8;
        unsigned int _g9;
        arr_g8 = word_prior_b;
        _g9 = i13_g5;
        _g7 = (*(arr_g8.data + _g9));
        acc_g6 = logSumExp2(acc_g6,_g7);
      }
      _g2 = acc_g6;
      _ga = _fo;
      _gb = _fz;
      _gc = i13_g5;
      _ew = logSumExp3(_ga,_gb,_gc);
      acc_ev += _ew;
   }
```

**Comment by zachsully** [comment]
The uniquify pass seems to be the quick fix.

What hakaru program is this example from?

**Comment by sabauma** [comment]
The example code comes from the [naive_bayes](https://github.com/zaxtax/naive_bayes/blob/master/nb_simp.hk) repo. The bug currently only manifests after an A-normalization pass, which is not included in the current Hakaru master branch.

**Comment by sabauma** [comment]
Using the `uniquify` pass seems an acceptable solution, though it would be good to make note of this assumption in the code generator. I am not certain there are no other points in the code that assume unique `varID`s implicitly.

**Comment by zaxtax** [comment]
Unique varIDs is assumed everywhere. At least it is also assumed in
disintegrate and expect.

**Comment by sabauma** [comment]
@zaxtax Where is this property enforced? The binding forms introduced by the Prelude don't guarantee globally unique varIDs.

**Comment by zaxtax** [comment]
It is done through calls to nextFreeOrBind which is defined in
https://github.com/hakaru-dev/hakaru/blob/master/haskell/Language/Hakaru/Syntax/ABT.hs

It's not perfect but it is used to make the assumption all varIDs are
unique.

**Comment by sabauma** [comment]
I think the high level conclusion of our discussion was that many parts of the compiler assume globally unique varIDs, and the observed failures are my fault. I will ensure that the results of the optimization pipeline are uniqified first.
