### ISSUE TITLE
simplification bug (negative Weight)

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#43]
The following Hakaru program
    x0 <~ uniform(1, 3)
    (match (0 < x0):
      true: reject. measure(real)
      false: return x0)

will simplify to (in Maple notation)

    Weight(-1/2,Uniform(1,0))

and will thus be rejected as an invalid program.

**Comment by yuriy0** [comment]
This was fixed by something recently. Since I'm not sure by what, I've added some test cases(fb6e656).
