### ISSUE TITLE
plate of berns doesn't parse

### ISSUE THREAD

**Issue by ccshan** [hakaru-dev/hakaru#45]
```
$ echo 'plate i of 10: bern(0.5)' | pretty
pretty: insertVarSet: variable is already assigned!
CallStack (from HasCallStack):
  error, called at haskell/Language/Hakaru/Syntax/Variable.hs:396:23 in hakaru-0.4.0-6kViTuEdGKS6SwZnYskeOG:Language.Hakaru.Syntax.Variable
```

@pravnar, does this have to do with your new implementation of `primBern` by any chance?

**Comment by pravnar** [comment]
Hm. I get the following output:

    $ echo 'plate i of 10: bern(0.5)' | pretty
    plate i of 10: 
     weight(1/2, return true) <|> 
     weight(real2prob((1 + negate(prob2real((1/2))))), return false)

**Comment by zaxtax** [comment]
I can replicate Ken's error. Praveen are you using the latest version? If
not do you have a sense which commit you built from so we can bisect?

**Comment by zaxtax** [comment]
This error was introduced by commit 7facbab265. I believe the use of binder
in primBern is what's causing the issues.

**Comment by zaxtax** [comment]
Alternatively, we can treat `bern` like `dirichlet` and just include the macro.

````
def bern(p prob):
    x <~ categorical([p, real2prob(1-p)])
    if x == 0: return false
    else: return true

plate i of 10: bern(0.5)
````

**Comment by JacquesCarette** [comment]
The biggest problem with macros is that they reduce readability -- especially in our setting where we do program transformations.   Plus you exhibit an anti-coding pattern:

    def bern(p prob:
        x <~ categorigal([p, real2prob(1-p)])
        return (x <> 0)

**Comment by zaxtax** [comment]
Just to be clear, `bern` is a macro right now. The only thing I am advocating is we remove the convenience of not having to type it's definition when we use `bern`. Currently it's definition is

````
def bern(p prob):
    x <~ categorical([p, real2prob(1 - p)])
    return [true, false][x]
```` 

Of course, I am happy to keep it that, or something like:

````
def bern(p prob):
    x <~ categorical([p, real2prob(1 - p)])
    return (x == 1)
````

**Comment by ccshan** [comment]
For the record, I believe that (contra @zaxtax) the bug was introduced not by 7facbab2655b687e16bfbc5f9b3a3fb749ff6b1d but by 75dde2d12e98e8b01fe41a06353afde5996d76a0

**Comment by zaxtax** [comment]
Yes I am not sure why I said the commit I did as there is nothing bern
related there.
