### ISSUE TITLE
Understand when int_assuming needs called

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#47]
See details at https://github.com/hakaru-dev/hakaru/commit/65d0dc5343b4a9949116a44262a4b0012f4ff31d#commitcomment-21609611

**Comment by yuriy0** [comment]
We now (08f1b6d5a0) understand this, and call it as needed. Maybe the particulars of this understanding should be documented better somewhere (but that is a seperate issue).
