### ISSUE TITLE
Version number in cabal is too restricted.

### ISSUE THREAD

**Issue by t3476** [hakaru-dev/hakaru#5]
It's very easy to encounter dependecy conflicts with other packages.

**Comment by zaxtax** [comment]
Great idea. Any packages in particular?

**Comment by t3476** [comment]
I use inline-r with hakaru.

**Comment by zaxtax** [comment]
So inline-r installs just fine from hakaru in master. Are you having a problem with the version on hackage? That was in out of date as we prepare for a major release.

**Comment by t3476** [comment]
Yes, I installed it from hackage. I'll wait for next release.
