### ISSUE TITLE
Domain.mpl doesn't work without opaquemodules=true

### ISSUE THREAD

**Issue by yuriy0** [hakaru-dev/hakaru#52]
Something about the module structure of Domain is broken, but it isn't clear how to fix it. `Domain:-Extract:-Bound` uses `Domain:-Has:-Bound` but without `opaquemodules=true`, Maple throws the error "Domain does not evaluate to a module". (This isn't the only occurrence of such an error, but it is the first which occurs at runtime). Trying to add the Domain submodules to the `uses` of other Domain submodules doesn't seem to work.

**Comment by JacquesCarette** [comment]
Could it be as silly as `Domain:-Extract` or `Domain:-Has` being declared local?

**Comment by yuriy0** [comment]
Yes, it turned out to be just that silly! Somehow I thought that exported symbols in `M:-X` would be in scope in other submodules of `M` even if `M:-X` is itself local.
