### ISSUE TITLE
Bug in `categorical` for the C backend

### ISSUE THREAD

**Issue by sabauma** [hakaru-dev/hakaru#53]
Below is a snippet of C code produced by HKC for the `categorical` statement for the `naive_bayes` benchmark, and is generated by [this](https://github.com/hakaru-dev/hakaru/blob/master/haskell/Language/Hakaru/CodeGen/Flatten.hs#L1211) portion of the C backend.

```C
r_h4 = ((((double)rand()) / ((double)RAND_MAX)) * exp(ws_h3));
ws_h3 = log(0);
it_h2 = 0;
while (1)
{
  if ((r_h4 < exp(ws_h3)))
  {
    out_g.weight = 0;
    out_g.sample = (it_h2 - 1);
    break;
  }
  ws_h3 = logSumExp2(ws_h3,_h1.data[it_h2]);
  it_h2++;
}
```

The problem is that, as implemented, this code causes a segmentation fault by accessing memory outside the valid range of `_h1.data`. In this example `_h1.length == 10` while `it_h2 == 9258`. Clearly out of bounds, but the error is not observable until we run afoul of memory access protection.

There two potential things wrong with this code which could cause the issue observed here.

1. Looking at the values in the `_h1` array which has type `struct array_prob`, all the values are ~4400. This is a somewhat non-sensical value for a probability (particularly in log domain). That seems odd to me, but perhaps this is valid for Hakaru. For the sake of categorical, all the elements have more or less the same probability, so it should be picking the values more or less uniformly for this example.
2. The termination condition `r_h4 < exp(ws_h3)` will never test true.  `exp(4000) == inf`, and `inf < inf` is always false. If the values in the `_h1` array are valid, then `categorical` needs to handle these cases. It looks like the implementation of `categorical` in LogFloatPrelude handles this by dividing every value by the maximum, then sampling from the resulting array.

**Comment by zachsully** [comment]
What is a "large" input? Is the input the size of the array or the positive reals in the array?

I haven't tested the old code (before the patch today) much to try to replicate this bug, but even with an array of 10,000,000 I do not segfault. This is a program I tried to break it with:

`categorical(array _ of 10000000: 10000)`

> the error is not observable until we run afoul of memory access protection
What do you mean here?

**Comment by sabauma** [comment]
In this case, "large" means that the probabilities in the given array are large. The input size of the array in my example above is only 10 elements.

When I say large, I mean that the physical representation of the probabilities in the runtime is large. That is, the value in memory of the log-spaced probabilities is >4000 in the case of `naive_bayes`. Thus, a naive exponentiation results in `+inf` being used in the termination criterion.

In your example, `categorical(array _ or 10000000: 10000)`, that `10000` is placed into log-space, so it is still safe to exponentiate by `categorical`.

> > the error is not observable until we run afoul of memory access protection
>
> What do you mean here?

The input array to categorical is small, only 10 elements. The program does not crash, however, unit it is indexed at its 9258th element. Everything between there and element 10 is garbage that the program accesses but will not crash the program. The benchmark segfaults only when it reaches a region of memory that has not been allocated to it by the OS.

I pushed a commit (f2e2b73) which I think fixes the issue, but a review would be welcome. It tries to copy the behavior of `categorical` in LogFloatPrelude.

**Comment by zachsully** [comment]
did this fix it for you? I finally got around to testing hkc with naive_bayes and am getting SIGSEGV errors. Were you able to create another program that fails?

**Comment by sabauma** [comment]
After these fixes, the naive_bayes benchmark works fine for me. Did naive_bayes fail with commit f2e2b73?

**Comment by zachsully** [comment]
That commit failed as well. Which commit of naive_bayes are you using?

**Comment by sabauma** [comment]
I should note that there is an error in the FFI specification that interfaces the C code with the Haskell code. The FFI specification is

```haskell
gibbsC :: ArrayStruct Double
       -> ArrayStruct Double
       -> ArrayStruct Int
       -> ArrayStruct Int
       -> ArrayStruct Int
       -> Int
       -> IO (ArrayStruct Double)
```

but the return type of the C code is `mdata_nat`. The segfault you are seeing is caused by trying to print the results of the C code in Haskell. I pushed a commit to the naive_bayes repo which should fix the problem.

**Comment by zachsully** [comment]
Yeah problem solved. Thanks!
