### ISSUE TITLE
Error on a deep solve-under-assuming call

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#58]
I was able to reproduce this (on master).

    kernelopts(opaquemodules=false):
    with(KB):
    kb := FOO(Introduce(j, HInt(Bound(`>=`, 0), Bound(`<=`, Let(Bucket(Fanout(Split(docUpdate = Hakaru:-idx(doc, i丙), Index(Hakaru:-size(word_prior), i丣, Hakaru:-idx(w, i丙), Add(1)), Nop()), Nop()), i丙 = 0 .. Hakaru:-size(w)-1), summary, piecewise(i = zNew丏, Hakaru:-idx(Hakaru:-fst(Hakaru:-fst(summary)), i丣), 0))-1))), Introduce(i丣, HInt(Bound(`>=`, 0), Bound(`<=`, Hakaru:-size(word_prior)-1))), Introduce(i, HInt(Bound(`>=`, 0), Bound(`<=`, Hakaru:-size(topic_prior)-1))), Introduce(zNew丏, HInt(Bound(`>=`, 0), Bound(`<=`, Hakaru:-size(topic_prior)-1))), Introduce(docUpdate, HInt(Bound(`>=`, 0))), Introduce(doc, HArray(HInt(Bound(`>=`, 0)))), Introduce(w, HArray(HInt(Bound(`>=`, 0)))), Introduce(z, HArray(HInt(Bound(`>=`, 0)))), Introduce(word_prior, HArray(HReal(Bound(`>=`, 0)))), Introduce(topic_prior, HArray(HReal(Bound(`>=`, 0))))):
    kb0 := build_unsafely(kb):
    #
    assert(And(i丣::integer, 0 <= i丣, i丣 <= Hakaru:-size(word_prior)-1), kb0);

It seems that i丣::integer gets passed to solve via

    solve({chill(i丣::integer)}, [i丣], 'useassumptions'=true) assuming ...

and that causes things to go Boom.

**Comment by JacquesCarette** [comment]
Issue to track the problem that @zachsully reported on ppaml-l.

**Comment by yuriy0** [comment]
Fixed by 26ecafa5ec (although this whole part of the code is still very fragile.)
