### ISSUE TITLE
Haddock documentation for data constructors of GADTs

### ISSUE THREAD

**Issue by wrengr** [hakaru-dev/hakaru#6]
At present, Haddock will fail to parse any documentation on data constructors for GADTs (including not-actually-GADTs using the GADT-syntax). This is a long outstanding issue in Haddock, as discussed in [the old trac ticket](http://trac.haskell.org/haddock/ticket/43) and [the ported-to-github ticket](https://github.com/haskell/haddock/issues/43). Apparently this will be fixed when GHC 7.12 ships, as discussed [in GHC Weekly News for 2015/07/21](https://ghc.haskell.org/trac/ghc/blog/weekly20150721) and [on phabricator](https://phabricator.haskell.org/D1086).

I'm filing this bug report here (1) to make a public note of this problem so others are aware of it, (2) to have a ticket number to put in comments making note of this issue, and (3) to remind us to fix it once we transition to GHC 7.12

**Comment by expipiplus1** [comment]
This is fixed now :)

**Comment by zaxtax** [comment]
Great! Does this mean hackage.org has been updated as well?

**Comment by JacquesCarette** [comment]
Do we support anything before 7.12?  Can we close this issue @zaxtax ?

**Comment by zaxtax** [comment]
We support back to 7.8

**Comment by JacquesCarette** [comment]
Any reason to do so other than 'we do'?

**Comment by zaxtax** [comment]
It makes it easier to install Hakaru. Even on the team frequently we are on
different versions of ghc and it hasn't been too hard to keep the the
system supported across many versions.

**Comment by JacquesCarette** [comment]
So if this is closed, does that mean we do not in fact officially support 7.8 and 7.10 anymore?

**Comment by zaxtax** [comment]
No, just that we can't build the documentation on those versions.
