### ISSUE TITLE
Different between C and haskell output.

### ISSUE THREAD

**Issue by rjnw** [hakaru-dev/hakaru#61]
Test hakaru program:
```
fn a array(prob):
   fn b nat:
      summate i from 0 to size(a):
      	   a[i] + nat2prob(b)
```
[hkc-output+printf](https://gist.github.com/rjnw/fc72b96293e68098c37a38aa17e840b5)
c-input:
```
a_b: [1.609438, 2.302585], b_c: 0
c-output: 22.180709779082402, prob2real: 4294967300.999997
```
haskell output
```
>:l examples/summate-prob.hs
> import Data.Number.LogFloat as LF
> import Data.Vector.Unboxed as UV
> prog (UV.fromList [(LF.logFloat 5.0), (LF.logFloat 10.0)]) 0
logFloat 15.0
> prog (UV.fromList [(LF.logToLogFloat 1.609438), (LF.logToLogFloat 2.302585)]) 0
logFloat 14.999999507889102
> LF.logFromLogFloat 14.999999507889102
2.7080501682948164
```

**Comment by ccshan** [comment]
The main problem (perhaps the only problem) is that the `unsigned int _r = b_c = 0` is used in the expression `log1p((_r - 1))`.  The subtraction causes underflow so we end up with a huge number.  One way to fix the problem is to change `1` to `1.0`.  The problem is illustrated by the difference between the two outputs below:
```c
#include <math.h>
#include <stdio.h>

int main() {
    unsigned int _r = 0;
    printf("%g\n", log1p(_r - 1));
    printf("%g\n", log1p(_r - 1.0));
    return 0;
}
```

**Comment by JacquesCarette** [comment]
Isn't the whole point of `log1p` that you call it with arguments close to 0 ?  `log1p(_r - 1.0)` is really bad, no?  Shouldn't that, in fact, be `log(_r)` ?

**Comment by ccshan** [comment]
@JacquesCarette: Well, @wrengr did write (https://list.indiana.edu/sympa/arc/ppaml-l/2016-07/msg00045.html)
> Just to underscore this point, always use log1p (and expm1) whenever you
> can. The difference is really striking. Even turns out it's often better to
> use log1p(x-1) than to use log(x) itself (and similarly for 1+expm1(x) in
> lieu of exp(x)). Again, the logfloat package is a good reference here.

But I just looked at the logfloat package source (https://hackage.haskell.org/package/logfloat-0.13.3.3/docs/src/Data-Number-LogFloat.html) and cannot find any occurrence of log1p(x-1) or 1+expm1(x). In particular:
* The logFloat function just uses log, and the fromLogFloat function just uses exp. So it seems @zachsully should make the corresponding changes to hkc.
* The (+) function uses log1p and exp. So it seems @zachsully should change line 11 of the generated code to use log1p(exp(...)), and line 61 of the generated code to use maxV_i+log1p(sum_k). The latter change would fix a math error.

**Comment by zachsully** [comment]
I recall the email from @wrengr and just put in a bunch of log1p's and expm1's at the time, but I still do not know what "the difference is really striking" means in this case or where to learn more,

In addition to those two fixes,

- line 58, I needed to remove this if-statement which doesn't occur in Wren's code. Faster code and more correct!

- I was testing this on the cmdline and wasn't taking the log of probabilities.

I'll request that someone else confirms it is working before closing this issue.

**Comment by zaxtax** [comment]
Does Rajan's test now work?

**Comment by rjnw** [comment]
Yes, I just checked it gives correct output.
Closing issue.
