### ISSUE TITLE
"Metropolis Hastings"

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#63]
The documentation has a very short section on this (too short to be useful as is). It should be augmented.

**Comment by JacquesCarette** [comment]
@zaxtax Could you help us by pointing out some useful source material that we can leverage here as well?

**Comment by zaxtax** [comment]
I think some of what is in `docs/transforms/mh/md` can be re-purposed for this section. The challenge for me was I didn't want to keep introducing new examples. I wanted a single one I could consistently use throughout the entire document.

**Comment by GenevaS** [comment]
I've expanded the content of this section (bf7c203e10ef8811c6cdec540f7a7373dfe35f73), but I don't know what other information you want included. I don't know if you want to jump into a Hakaru example here, since it appears to be a more advanced topic. I have included a link that will redirect them to the mh page though.

**Comment by JacquesCarette** [comment]
I'm fine with being somewhat minimalistic, as long as the section contains enough links for the interested reader (both internal, i.e. the section on `mh`, but also external to good sources that describe MH).  I believe @zaxtax knows of good such sources.  Wikipedia always being a half reasonable fallback position.

**Comment by zaxtax** [comment]
I think “Introduction to Monte Carlo methods” by the late David Mackay is the one most of us are fond of for introducing MH.

**Comment by GenevaS** [comment]
I've added a reference to Dr. MacKay's paper in the page's references (99f85a66f5a4675f23e6a3dfb109aad8e9e1421e). Was this the only thing let for this section, or is more information needed?

**Comment by JacquesCarette** [comment]
I'm happy with it.

**Comment by zaxtax** [comment]
Me too. I just left one comment, but otherwise great!

**Comment by zaxtax** [comment]
The update looks great!
