### ISSUE TITLE
Installing `mkdocs`

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#64]
See commit d764331c for a discussion on properly installing `mkdocs`.

**Comment by GenevaS** [comment]
I have created a command line script to install mkdocs on Windows (cc7ae425db878e1c05ff5d973953e464fb8fd7d5). What other operating systems should I make a script for? Linux?

**Comment by JacquesCarette** [comment]
Yes please.  And it should work on Mac too.

**Comment by GenevaS** [comment]
I have created a script for OSX (3497f99e6dfc4368fd32dd9558a27a2df105714e), but I'll need to find a Linux machine to test the last script.

**Comment by GenevaS** [comment]
I wrote what I think would be the script for Linux (42a2c1d198219adeb27d53f19e74108a60635e0f) but I still want to test it if possible.

**Comment by zaxtax** [comment]
Nice. So there is a lot of repetition between the scripts. Maybe installing mkdocs can itself be part of the installation instructions?

**Comment by GenevaS** [comment]
I wrote them as separate scripts so that whoever needs them doesn't have to worry about changing the script for their particular OS. They are almost identical though, so if you want me to condense them and write OS specific instructions as part of the script's comments, I can do that too.

I don't know why someone outside the Hakaru team would need these, so I don't why they should be in the Hakaru installation instructions.

**Comment by zaxtax** [comment]
That's a good point. It's just short of comments the scripts are identical. I should note the documentation does have material that is only interesting to developers so it's not without precedent to put it somewhere there.

**Comment by JacquesCarette** [comment]
I agree that we can have documentation for different classes of people; we should try hard to make it clear who the audience is for each page.

**Comment by GenevaS** [comment]
I've added instructions for installing `pip` and MkDocs in the "Adding a Language Feature" page (eb02ef760dde56acd7f4989dbb2082cac13d455a). Is this preferable to the scripts themselves?

**Comment by zaxtax** [comment]
Yes.

**Comment by GenevaS** [comment]
Alright, I will remove the scripts from the repository.

**Comment by GenevaS** [comment]
Should this issue be closed or are there other items to address for installing MkDocs?
