### ISSUE TITLE
Add option to Hakaru command to print weights

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#68]
Since some of our samplers produce rather non-uniform weights, these need to be printed to be able to properly understand the measure at hand.

- Whether weights should be on by default is one question; certainly they should be easy to `sed`/`awk` out.
- A warning when the weights are not printed but are not "the same" should be given.

**Comment by JacquesCarette** [comment]
Looks like this is now done?  Or just the first part?

**Comment by zaxtax** [comment]
I did the first part. I don't think the second part is feasible.

**Comment by JacquesCarette** [comment]
It's feasible, just expensive.  So probably best to have weights be on by default, then it is in the hands of the user to decide to turn them off.

**Comment by zaxtax** [comment]
Well there might be a way to figure that out just from the AST, but I'd rather re-visit this later.
