### ISSUE TITLE
code in hakaru tutorial (0.1.4) gives suspicious coefficients

### ISSUE THREAD

**Issue by tranma** [hakaru-dev/hakaru#7]
I tried the code for fitting curves in the tutorial (http://indiana.edu/~ppaml/HakaruTutorial.html), particularly:

```
expectations l = map (mean . V.fromList) (transpose l)

poly1d weights x = poly weights x 1
   where poly [] x acc = 0
         poly (w:ws) x acc = w*acc + (poly ws x acc*x)

cubic :: [Double] -> Measure [Double]
cubic x = do
    w <- replicateM 4 $ unconditioned (normal 0 2)
    y <- mapM (conditioned . (\x -> normal (poly1d w x) 1)) x
    return w

burn = 5000

do
   l <- mcmc (cubic x) (map (Just . toDyn . Lebesgue) y)
   let means = expectations $ take 1000 $ drop burn l
   return $ chart (poly1d means) (zip x y)
```

This is the coefficients I got back:

```
[3.013056283406498e-2,3.013056283406498e-2,3.013056283406498e-2,3.013056283406498e-2]
```

They are all the same, regardless of what data and what curve I used.

Did I do something wrong? This is highly....suspicious.

**Comment by zaxtax** [comment]
That is odd. What exactly did you run?

**Comment by zaxtax** [comment]
It looks like what is happening is that the mcmc chain is not exploring properly. Can you try restarting the notebook? One of the issues with how that version of hakaru is written is that the seed is set once for the entire notebook.

**Comment by tranma** [comment]
ah, I just copypasted the code and used my own data, not loading the notebook.

**Comment by zaxtax** [comment]
If you are interested in sharing your data in a gist, I can try to
replicate your problem?

**Comment by tranma** [comment]
this happened with the data provided at the beginning of the notebook as well, not just custom data.

(My data is actually just run-time measurements for different algorithms, I could print them out if it helps)

**Comment by zaxtax** [comment]
That's odd. When I just ran this on my machine I get the following:

> l <- mcmc (cubic x) (map (Just . toDyn . Lebesgue) y)
> let means = expectations $ take 1000 $ drop 5000 l
> means
[0.11134157839651367,-1.1298206916751103,7.436443313258073e-2,0.9467708047335495]

**Comment by tranma** [comment]
hm, this is on GHC 7.10.2. Do you run 7.10 or 7.8?

To compile hakaru-0.1.4 on GHC 7.10, I just added a default applicative instance here:

```
--- a/Language/Hakaru/ImportanceSampler.hs
+++ b/Language/Hakaru/ImportanceSampler.hs
@@ -15,6 +15,7 @@ import Language.Hakaru.Sampler (Sampler, deterministic, smap, sbind)

 import qualified System.Random.MWC as MWC
 import Control.Monad.Primitive
+import Control.Monad(ap)
 import Data.Monoid
 import Data.Dynamic
 import System.IO.Unsafe
@@ -31,10 +32,17 @@ bind measure continuation =
     sbind (unMeasure measure conds)
           (\(a,cds) -> unMeasure (continuation a) cds))

+instance Functor Measure where
+  fmap f x = x >>= return . f
+
 instance Monad Measure where
   return x = Measure (\conds -> deterministic (point (x,conds) 1))
   (>>=)    = bind

+instance Applicative Measure where
+  pure = return
+  (<*>) = ap
```

which shouldn't have any semantics impact at all.

**Comment by zaxtax** [comment]
I am running on 7.8.3, but those instances shouldn't break anything. Were
you using the Importance Sampler or Metropolis?

**Comment by tranma** [comment]
I used Metropolis, so it shouldn't matter anyway.

**Comment by zaxtax** [comment]
I agree. Not sure the ghc version should make either.

**Comment by zaxtax** [comment]
I finally figured it out! Deep in the code we used MWC.create instead of MWC.createSystemRandom. This will be fixed in the next version!
