### ISSUE TITLE
optimization passes and buckets

### ISSUE THREAD

**Issue by zachsully** [hakaru-dev/hakaru#70]
I just pushed a commit (9836c0646173f2118ac1502ce8207d40e8f0cd81) that adds the optimization passes to `summary` and `compile`. The Haskell generated code demonstrates the problem the best.

Here is the output of `summary examples/summary.hk -o -` WITHOUT optimizations:
```
prog = 
  lam $ \ K0 ->
  lam $ \ z1 ->
  lam $ \ t2 ->
  (array K0 $
         \ k3 ->
         let_ (bucket (nat_ 0)
                      (size z1)
                      ((r_index (\ () -> K0)
                                (\ (i5,()) -> z1 ! i5)
                                (r_add (\ (i5,(k6,())) -> t2 ! i5))))) $ \ summary4 ->
         summary4
         ! k3)
```

And here is the output of the bucket optimized version `summary -O examples/summary.hk -o -`:
```
prog = 
  lam $ \ K21 ->
  lam $ \ z22 ->
  lam $ \ t23 ->
  (array K21 $ \ k24 -> summary19 ! k24)
```

It calls a variable `summary19` which is never bound. HKC refuses to generate code in this case,
throwing the error `hkc: lookupIdent: var not found --Variable "summary" (Nat 19) (SArray SReal)
`. The Haskell generated code will fail at compile time.

**Comment by zaxtax** [comment]
I'm curious are do these optimizations do the right thing if you don't summary the programs?

**Comment by zachsully** [comment]
Here is `compile` with and without optimizations respectively:

```
prog = 
  lam $ \ K11 ->
  lam $ \ z12 ->
  lam $ \ t13 ->
  let_ (nat2real (nat_ 0)) $ \ x14 ->
  let_ (size z12) $ \ x15 ->
  (array K11 $
         \ k16 ->
         summate (nat_ 0)
                 x15
                 (\ i17 ->
                  let_ (t13 ! i17) $ \ x18 ->
                  let_ (z12 ! i17) $ \ x19 ->
                  let_ (x19 == k16) $ \ x20 ->
                  case_ x20 [branch ptrue (x18), branch pfalse (x14)]))
```

Without:
```
prog = 
  lam $ \ K0 ->
  lam $ \ z1 ->
  lam $ \ t2 ->
  (array K0 $
         \ k3 ->
         summate (nat_ 0)
                 (size z1)
                 (\ i4 ->
                  case_ (z1 ! i4 == k3)
                        [branch ptrue (t2 ! i4), branch pfalse (nat2real (nat_ 0))]))
```

Just eyeballing it quickly, it appears all of the variables that are called are bound.

**Comment by zachsully** [comment]
The problem can be solved by removing the `normalize` transformation, giving the code:

```
prog = 
  lam $ \ K7 ->
  lam $ \ z8 ->
  lam $ \ t9 ->
  let_ (size z8) $ \ x10 ->
  let_ (bucket (nat_ 0)
               x10
               ((r_index (\ () -> K7)
                         (\ (i11,()) -> z8 ! i11)
                         (r_add (\ (i12,(k13,())) -> t9 ! i12))))) $ \ x14 ->
  (array K7 $ \ k15 -> x14 ! k15)
```

So it may just require added bucket cases for that pass. There might be a problem with the catch all for `normalize` because this issue arouse when a new construct was added to Hakaru's AST.

**Comment by zaxtax** [comment]
That's a good point, we might need to add the Bucket case to `normalize`. I'm unfamiliar with what that pass does but we can try to figure it out.

**Comment by ccshan** [comment]
I'm looking at ANF.hs and working on fixing `normalizeTerm term = const ($ syn term)` in a general way.

**Comment by ccshan** [comment]
I'm not an expert on the `normalize` transformation, so I'd appreciate any confirmation on whether this commit 4b5584437f96d240e9932b3cd6c0f7283340f0cf fixed or broke anything.

**Comment by JacquesCarette** [comment]
If only there were enough tests to get some confidence that at least you didn't break anything... 😈

**Comment by zachsully** [comment]
The two cases I ran into problems were `hkc -S -O2 examples/summary.hk` and `hkc -S -O2 naive_bayes/nb_simp.hk`.

These both compile now. Thanks!
