### ISSUE TITLE
Maple and Haskell have a different understanding of Lebesgue

### ISSUE THREAD

**Issue by yuriy0** [hakaru-dev/hakaru#74]
Simplifying the following program:
```
x0 <~ lebesgue()
(match (42 < x0):
  true: return x0
  false: reject. measure(real))
```
gives
```
Sent to Maple:
use Hakaru, NewSLO in timelimit(90, RoundTrip(Bind(Lebesgue(-infinity,infinity), x0, case(42 < x0, Branches(Branch(PDatum(true, PInl(PDone)), Ret(x0)), Branch(PDatum(false, PInr(PInl(PDone))), Msum())))), HMeasure(HReal()), _command=Simplify)) end use;
Returning from Maple:
Lebesgue(42,infinity)
lebesgue
```

The Hakaru typechecker doesn't seem to accept this form of `lebesgue` at all:
```
$ echo "lebesgue(1,2)" | pretty -
Type Mismatch:
expected function type, found SMeasure SReal
```
so I'm not sure how it ends up discarding the `42,infinity` part.

It seems that Maple is using its own special syntax for Lebesgue, which gets misunderstood by Haskell. This is really two issues. Haskell needs to issue a parse error or translate the program correctly. I'm not sure if Maple should be producing such a Hakaru program (if it even is a correct Hakaru program).

**Comment by zaxtax** [comment]
Yep lebesgue in maple takes arguments and in Haskell it doesn't. This is a long needed change that involves changing the lebesgue primitive on the Haskell side.

**Comment by JacquesCarette** [comment]
So who should own this issue (and hopefully fix it)?

**Comment by zaxtax** [comment]
Anyone who is willing to fix it. I can make a simple hack converting it to uniform for now if it's blocking something.

**Comment by JacquesCarette** [comment]
I'm guessing that this is now leading to test failures (or will very soon) once we switch some tests from being Maple-only to using external Hakaru syntax as the principal means of doing things.

**Comment by zaxtax** [comment]
Alright tag me

**Comment by yuriy0** [comment]
This (dc424b8114924f7c99e5955ab17efa8a39c3a170) change should fix this this issue. If somebody could verify that the correct thing is done in `Disintegrate.hs` and `Expect.hs`, this can be closed.

**Comment by ccshan** [comment]
I'd like to get rid of the "terrible hack" in `L.H.Parser.SymbolResolve` to preserve the old concrete syntax `lebesgue` without arguments. How about we just update the 6 places in `examples/` where that old syntax is used? (If not that, then I would put the hack in `resolveAST` so that the hack affects only `Concrete` parsing, not `Maple` parsing.)

Also, `counting` deserves the same treatment as `lebesgue`.

**Comment by zaxtax** [comment]
Just to clarify when both arguments to `counting` or `lebesgue` are finite, what do you want that to mean?

**Comment by yuriy0** [comment]
Thanks for the fixes!

> I'd like to get rid of the "terrible hack" in L.H.Parser.SymbolResolve to preserve the old concrete syntax lebesgue without arguments. How about we just update the 6 places in examples/ where that old syntax is used?

I think this is the best solution. I just didn't want to break any programs without warning. I guess this is the warning. I'll get rid of the hack and update the needed programs. 

> Also, counting deserves the same treatment as lebesgue.

I've made a separate issue (#93) for that.

**Comment by ccshan** [comment]
The integral of a function `h` with respect to the measure `lebesgue(a,b)` is `int(h(x), x=a..b)`

The integral of a function `h` with respect to the measure `counting(a,b)` is `sum(h(x), x=a..b-1)` (note that the upper bound `b` is exclusive)

**Comment by ccshan** [comment]
This issue is done, no?

**Comment by yuriy0** [comment]
I believe so.
