### ISSUE TITLE
LDA is not "Bayesian Naive Bayes"

### ISSUE THREAD

**Issue by cscherrer** [hakaru-dev/hakaru#76]
Regarding the description of LDA [here](http://hakaru-dev.github.io/examples/)...

Looks like it's just very drafty documentation, but it's worth noting that 
* LDA is not an instance of Naive Bayes
* For NB instances, a "Bayesian" qualifier is redundantly redundant :)

**Comment by zaxtax** [comment]
That page should probably just be rewritten.

**Comment by JacquesCarette** [comment]
What should it be rewritten to?  Maybe @GenevaS can do it, with instructions from @zaxtax and @cscherrer ?

**Comment by cscherrer** [comment]
Quick fix:
1. Expand LDA to "Latent Dirichlet Allocation"
2. Take out "a form of Bayesian Naives Bayes"
3. Replace (2) with a link to the original LDA paper

**Comment by GenevaS** [comment]
Which paper would that be?

**Comment by cscherrer** [comment]
Oops sorry. Here, [this one](http://www.jmlr.org/papers/volume3/blei03a/blei03a.pdf)

**Comment by GenevaS** [comment]
Ok, those changes have been implemented in 14990fccf487d8a02a5bf4cd0fc8bdefba05e75c and pushed to the Hakaru docs.

**Comment by cscherrer** [comment]
Thanks Geneva, closing this issue
