### ISSUE TITLE
Pretty printed program is invalid concrete syntax

### ISSUE THREAD

**Issue by yuriy0** [hakaru-dev/hakaru#77]
`RoundTrip.hs/rmProg4` is not valid when converted to concrete syntax, with e.g.:

```
> writeFile "examples/rmProg4.hk" $ show $ pretty $ expandTransformations (rmProg4 @(TrivialABT Term))
```

in particular, it contains:
```
match fn x40 pair(real, real): ...
```

which causes the error: 
```
"<input>" (line 2, column 5):
unexpected '='
expecting operator or end of input
```

**Comment by JacquesCarette** [comment]
Who knows the pretty-printer best?  @zaxtax or @ccshan ?

**Comment by zaxtax** [comment]
This error is probably my fault

**Comment by zaxtax** [comment]
Also I'm not sure of any world where matching on a function makes any sense. I'll investigate.

**Comment by yuriy0** [comment]
This seems to be fixed (but of course the program doesn't parse any quicker - see #78 for that) by 155d7729e2a16b0. And a few test cases: b6512685 and 13bdc12d5. 

The difference here essentially boiled down to 

```
match (fn x real: x, fn y real: y):
  (a,b): a(1)+b(2)
```
vs. 
```
match fn x real: x, fn y real: y:
  (a,b): a(1)+b(2)
```

The latter program is not valid syntax, as well as ambiguous.

**Comment by JacquesCarette** [comment]
I am curious as to why we have this kind of higher-order functions in our models.  [Don't get me wrong, I love higher-order!].  But it can be needlessly abused too.  And is much harder to reason about.

So why does `rmProg4` have higher-order bits?  Is it fundamental or accidental?

**Comment by yuriy0** [comment]
I can't say I have a definite answer. It certainly looks like the program was generated by a machine. It may just be an artifact of that generation process.

The program `rmProg4` looks like so:
```
(fn x42 pair(real, real): 
  x4 = (fn x41 pair(prob, prob): < giant thing spanning ~270 lines > )
  (fn x3 pair(prob, prob): 
    x0 <~ (match x3: 
            (x1, x2): 
             weight(1/2,
                    x0 <~ uniform(3, 8)
                    return (real2prob(x0), x2)) <|> 
             weight(1/2,
                    x0 <~ uniform(1, 4)
                    return (x1, real2prob(x0))))
    return (x0, (x4(x0) / x4(x3))))) 
```

The body of `x4` has lots of expression of the form 
```
(return x1,
   (fn x0 pair(prob,prob) -> prob: x0(x1)))
```
at the leaves of large nested `match`es.

While it is certainly strange to return both `x1` and and `x1` in a CPS type wrapper, `x1` is never actually used. The final line of `x4` is: 
```
  x4 = (fn x41 pair(prob, prob): .....
                    (x1, x2): x2((fn x0 pair(prob, prob): 1))))
```

There are also lots of inlinings of `fst` and `snd`:
```
(match x5: (x0, x1): x1)(x2)
```
Perhaps indicative of the original program containing lots of `fst` and `snd` as opposed to pattern matching directly to access the components. 

Finally, note the two occurences of `x4` on the very last line. I suppose the use of "functional programming" here is meant to allow us to simplify `x4` once instead of twice. (Although, this isn't higher order; and more importantly, we don't take advantage of it at all.)

**Comment by JacquesCarette** [comment]
Aha!  So `rmProg4` is a very old program, produced back in the day where a lot of CPS was used.  And higher-order eliminators for products.

Now what is passed to Maple is first-order.  And `rmProg4` was generated by some old process.  We should remember what that was, re-run it, and put the new one in its place.
