### ISSUE TITLE
Testing equivalence of Hakaru programs

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#79]
As issue #75 mentions, an issue from long ago is resurfacing:  how do we test that two Hakaru programs are 'trivially' equivalent.  I think we'd like to be able to abstract over alpha-equivalence, commutativity-associativity of + and * and && and || .  We might want to not worry about some amount of polynomial arithmetic.  Although I must admit that I would like to not consider 

    x + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 +0

equivalent to

    x

!  [The point is that, in a test, we'd want to know if we're spitting out lots of `+ 0` that we were not expecting.]

Suggestion: we create a new (simple) data-type in Haskell which is first-order (we can use gensym to generate fresh names) that represents Hakaru programs, for the sole purpose of equivalence testing.  This would be a 'throwaway' representation.  Its only guarantee would be that it produces a 'normal form' with respect to a set of rules (such as alpha-equivalence, etc) that we deem to be 'trivial'.

**Comment by ccshan** [comment]
It seems @yuriy0 is working on this (9c7dc0eab156a342801909b521469ec06da899f4)? Thanks!

**Comment by JacquesCarette** [comment]
Yes, he has been.  Not quite sure the exact status, but there definitely has been forward progress.

**Comment by yuriy0** [comment]
> It seems @yuriy0 is working on this (9c7dc0e)? Thanks!

This was the first step; that change should handle associativity and commutativity for `NAryOp`s. It is the slower and simpler of the two proposed implementations at last weeks meeting. This implementation is essentially what you called 'bipartite graph matching'. The other implementation probably requires changing all of `alphaEq` to return an `Ordering`. 

This does not address the issue of `x + negate(y)` vs `x - y`; or of polynomial normals form, e.g.: 

```
### Failure in: 5:RoundTrip:2:16:t46
x0 <~ normal(4, 5)
return (match (x0 < 3): 
         true: (x0 * x0)          --
         false: (x0 - 1))
but got:
x03 <~ normal(4, 5)
return (match (x03 < 3): 
         true: (x03 ^ 2)          --
         false: (x03 - 1))
```

but at least the latter is highly non-trivial.

**Comment by ccshan** [comment]
Are we done here?

**Comment by JacquesCarette** [comment]
alpha, associativity and commutativity are done.  polynomial normal form is not.  But it could be split off into a separate issue, as it is a problem for fewer tests.

**Comment by ccshan** [comment]
And I don't even know that we want polynomial normal form for testing equivalence...

**Comment by JacquesCarette** [comment]
We want to at least deal with `-` sanely.  The rest is indeed up for discussion.

**Comment by ccshan** [comment]
Maybe the problem with `-` is that the Maple parser should parse `a-b` in Maple into negation in Hakaru?

**Comment by zaxtax** [comment]
There is no minus in the Hakaru AST. There is only addition with negation
applied to the second argument.

On Tue, Jun 20, 2017 at 10:12 PM, Chung-chieh Shan <notifications@github.com

**Comment by yuriy0** [comment]
The changes to literals allow us to specify precisely the program which is produced by Maple (i.e. in terms of `x + negate(y)` vs `x - y`) so this is fixed, at least until we find two equivalent programs which differ by more than `x + negate(y)` vs `x - y`.
