### ISSUE TITLE
Create a gitter room for hakaru

### ISSUE THREAD

**Issue by suhailshergill** [hakaru-dev/hakaru#8]
[Gitter](http://gitter.im) allows you to create chatrooms linked to specific github repositories allowing you to reference issues etc and have more live discussions.
Once a room is created, it allows you the option to create a pull request to add a badge/link. See the README for https://github.com/suhailshergill/extensible-effects for an example (pull request in question: https://github.com/suhailshergill/extensible-effects/pull/36).

i would be happy to help get this set up, but i believe you need to be part of the organization (hakaru-dev in this case) to do so.

**Comment by zaxtax** [comment]
I don't think this matches anybody's workflow on the project.
