### ISSUE TITLE
Add travis support

### ISSUE THREAD

**Issue by suhailshergill** [hakaru-dev/hakaru#9]
[Travis](http://travis-ci.org) is a continuous integration server which offers a free service to allow you to run build tests and have the ability to reflect its state in the repository. For reference see https://github.com/suhailshergill/extensible-effects (note the [![Build Status](https://travis-ci.org/suhailshergill/extensible-effects.svg?branch=master)](https://travis-ci.org/suhailshergill/extensible-effects) badge).

below is an outline of a possible plan:
- [x] add a build file which captures all the tests/checks we want to run on the CI system. For reference see https://github.com/suhailshergill/extensible-effects/blob/develop/Makefile#L66. Note: this step is optional and is not strictly necessary
- [x] add a `.travis.yml` file which configures environment and invokes the tests which need to be run (either by directly specifying or referencing build file if one exists). For reference see https://github.com/suhailshergill/extensible-effects/blob/develop/.travis.yml
- [ ] enable build in travis-ci
- [ ] Profit! ;)

let me know if the above makes sense, and i would be happy to contribute and lend a hand.

**Comment by zaxtax** [comment]
This sounds like a good idea. I want to get our test suite hooked up and I think we should do this.

**Comment by wrengr** [comment]
@zaxtax If you want to do this, take a look at the .travis.yml files in my other Haskell projects (e.g., [the one for bytestring-lexing](https://github.com/wrengr/bytestring-lexing/blob/master/.travis.yml)). They include stuff for how to simultaneously build against multiple different versions of GHC. The biggest trick is getting the total build time for all the dependencies down to something reasonable.

If you want pointers, I'll be around this week; though I won't have time to work on it myself until a couple weeks out.

**Comment by zaxtax** [comment]
So, one concern I have is how do we specify conditional testing. For example, we have tests that only pass if a version of maple is installed. What's the standard way to disable those from cabal?

**Comment by suhailshergill** [comment]
depends on where you're doing the check to ensure that maple is/isn't
installed, but you could use flags in cabal to selectively enable/disable
portions. these flags could be passed in via the invocations in travis

On Thu, Feb 18, 2016 at 11:20 PM, zaxtax <notifications@github.com> wrote:

> So, one concern I have is how do we specify conditional testing. For
> example, we have tests that only pass if a version of maple is installed.
> What's the standard way to disable those from cabal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakaru-dev/hakaru/issues/9#issuecomment-186043540>.
>



-- 
Suhail
